import React from 'react';
import { AvailabilityStatus } from '../types';
import { CheckCircle2, Clock, Sparkles, Navigation } from 'lucide-react';

interface StatusBadgeProps {
  status: AvailabilityStatus;
  size?: 'sm' | 'md' | 'lg';
}

export const StatusBadge: React.FC<StatusBadgeProps> = ({ status, size = 'md' }) => {
  const sizeClasses = {
    sm: 'text-xs px-2 py-0.5 gap-1',
    md: 'text-xs px-2.5 py-1 gap-1.5',
    lg: 'text-sm px-3 py-1.5 gap-2',
  }[size];

  switch (status) {
    case 'CONFIRMED_AVAILABILITY':
      return (
        <span 
          title="Physically verified and reserved by authorized laboratory staff"
          className={`inline-flex items-center font-semibold rounded-full bg-emerald-950/80 text-emerald-400 border border-emerald-500/40 shadow-sm shadow-emerald-900/20 ${sizeClasses}`}
        >
          <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
          <span>Confirmed Availability</span>
        </span>
      );

    case 'REPORTED_AVAILABILITY':
      return (
        <span 
          title="Raw batch record reported by facility or external adapter. Awaiting physical lab confirmation."
          className={`inline-flex items-center font-medium rounded-full bg-amber-950/80 text-amber-300 border border-amber-500/40 shadow-sm shadow-amber-900/20 ${sizeClasses}`}
        >
          <Clock className="w-3.5 h-3.5 text-amber-400 shrink-0" />
          <span>Reported Availability</span>
        </span>
      );

    case 'PREDICTED_AVAILABILITY':
      return (
        <span 
          title="Projected forward-looking supply calculated by Scikit-Learn Machine Learning model"
          className={`inline-flex items-center font-semibold rounded-full bg-purple-950/80 text-purple-300 border border-purple-500/40 shadow-sm shadow-purple-900/20 ${sizeClasses}`}
        >
          <Sparkles className="w-3.5 h-3.5 text-purple-400 shrink-0" />
          <span>Predicted Availability</span>
        </span>
      );

    case 'RECOMMENDED_ACTION':
      return (
        <span 
          title="Algorithmic dispatch or transfer advisory generated by multi-criteria optimization engine"
          className={`inline-flex items-center font-medium rounded-full bg-blue-950/80 text-blue-300 border border-blue-500/40 shadow-sm shadow-blue-900/20 ${sizeClasses}`}
        >
          <Navigation className="w-3.5 h-3.5 text-blue-400 shrink-0" />
          <span>Recommended Action</span>
        </span>
      );

    default:
      return (
        <span className={`inline-flex items-center rounded-full bg-slate-800 text-slate-300 border border-slate-700 ${sizeClasses}`}>
          {status}
        </span>
      );
  }
};
