import React from 'react';
import { AvailabilityStatus } from '../types';
import { CheckCircle2, Clock, Sparkles, Navigation, Lock } from 'lucide-react';

interface StatusBadgeProps {
  status: AvailabilityStatus | 'RESERVED' | string;
  size?: 'sm' | 'md' | 'lg';
}

export const StatusBadge: React.FC<StatusBadgeProps> = ({ status, size = 'md' }) => {
  const sizeClasses = {
    sm: 'text-[11px] px-2 py-0.5 gap-1',
    md: 'text-xs px-2.5 py-0.5 gap-1.5',
    lg: 'text-sm px-3 py-1 gap-2',
  }[size];

  switch (status) {
    case 'CONFIRMED_AVAILABILITY':
    case 'CONFIRMED':
      return (
        <span 
          title="Physically verified and confirmed by authorized laboratory staff"
          className={`inline-flex items-center font-semibold rounded-full bg-emerald-50 text-emerald-700 border border-emerald-300 shadow-xs ${sizeClasses}`}
        >
          <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
          <span>CONFIRMED</span>
        </span>
      );

    case 'REPORTED_AVAILABILITY':
    case 'REPORTED':
      return (
        <span 
          title="Reported by facility or external portal feed. Awaiting physical lab cross-confirmation."
          className={`inline-flex items-center font-medium rounded-full bg-amber-50 text-amber-800 border border-amber-300 shadow-xs ${sizeClasses}`}
        >
          <Clock className="w-3.5 h-3.5 text-amber-600 shrink-0" />
          <span>REPORTED (UNVERIFIED)</span>
        </span>
      );

    case 'RESERVED':
      return (
        <span 
          title="Blood units actively held for active clinical requisition or cross-match"
          className={`inline-flex items-center font-semibold rounded-full bg-blue-50 text-blue-800 border border-blue-300 shadow-xs ${sizeClasses}`}
        >
          <Lock className="w-3.5 h-3.5 text-blue-600 shrink-0" />
          <span>RESERVED</span>
        </span>
      );

    case 'PREDICTED_AVAILABILITY':
      return (
        <span 
          title="Projected forward-looking supply calculated by Scikit-Learn Machine Learning model"
          className={`inline-flex items-center font-semibold rounded-full bg-purple-50 text-purple-700 border border-purple-300 shadow-xs ${sizeClasses}`}
        >
          <Sparkles className="w-3.5 h-3.5 text-purple-600 shrink-0" />
          <span>PREDICTED AI</span>
        </span>
      );

    case 'RECOMMENDED_ACTION':
      return (
        <span 
          title="Algorithmic dispatch or transfer advisory generated by multi-criteria optimization engine"
          className={`inline-flex items-center font-medium rounded-full bg-indigo-50 text-indigo-700 border border-indigo-300 shadow-xs ${sizeClasses}`}
        >
          <Navigation className="w-3.5 h-3.5 text-indigo-600 shrink-0" />
          <span>RECOMMENDED</span>
        </span>
      );

    default:
      return (
        <span className={`inline-flex items-center rounded-full bg-slate-100 text-slate-700 border border-slate-300 ${sizeClasses}`}>
          {status}
        </span>
      );
  }
};
