/**
 * 100 Synthetic Blood Inventory Records matching supabase_blood_inventory_100_seed.sql
 * DEMO DATA ONLY: Synthetic dataset for academic demonstrations & local testing.
 */

export interface BloodInventoryUnit {
  id: string;
  blood_group: string;
  rh_type: 'Positive' | 'Negative';
  component: 'Packed Red Blood Cells' | 'Whole Blood' | 'Platelets' | 'Fresh Frozen Plasma';
  quantity_ml: number;
  collection_date: string;
  expiration_date: string;
  screening_status: 'cleared' | 'pending';
  status: 'available' | 'reserved' | 'used' | 'expired';
  blood_bank_id: string;
  blood_bank_name: string;
  city: string;
  storage_location: string;
  created_at: string;
}

const getRelativeDate = (offsetDays: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

interface RawItem {
  id: string;
  blood_group: string;
  rh_type: 'Positive' | 'Negative';
  component: 'Packed Red Blood Cells' | 'Whole Blood' | 'Platelets' | 'Fresh Frozen Plasma';
  quantity_ml: number;
  col_offset: number;
  exp_offset: number;
  screening_status: 'cleared' | 'pending';
  status: 'available' | 'reserved' | 'used' | 'expired';
  blood_bank_id: string;
  blood_bank_name: string;
  city: string;
  storage_location: string;
}

const rawRecords: RawItem[] = [
  {
    "id": "BL-1001",
    "blood_group": "O+",
    "rh_type": "Positive",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -35,
    "exp_offset": -5,
    "screening_status": "cleared",
    "status": "expired",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1002",
    "blood_group": "O+",
    "rh_type": "Positive",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 6,
    "screening_status": "cleared",
    "status": "reserved",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1003",
    "blood_group": "O+",
    "rh_type": "Positive",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 14,
    "screening_status": "cleared",
    "status": "used",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1004",
    "blood_group": "O+",
    "rh_type": "Positive",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -2,
    "exp_offset": 10,
    "screening_status": "pending",
    "status": "available",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1005",
    "blood_group": "O+",
    "rh_type": "Positive",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -30,
    "exp_offset": 1,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1006",
    "blood_group": "O+",
    "rh_type": "Positive",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -30,
    "exp_offset": 3,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1007",
    "blood_group": "O+",
    "rh_type": "Positive",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 5,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1008",
    "blood_group": "O+",
    "rh_type": "Positive",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -25,
    "exp_offset": 7,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1009",
    "blood_group": "O+",
    "rh_type": "Positive",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -20,
    "exp_offset": 9,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1010",
    "blood_group": "O+",
    "rh_type": "Positive",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 12,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1011",
    "blood_group": "O+",
    "rh_type": "Positive",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -10,
    "exp_offset": 18,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1012",
    "blood_group": "O+",
    "rh_type": "Positive",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -10,
    "exp_offset": 26,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1013",
    "blood_group": "O-",
    "rh_type": "Negative",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -35,
    "exp_offset": -5,
    "screening_status": "cleared",
    "status": "expired",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1014",
    "blood_group": "O-",
    "rh_type": "Negative",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 6,
    "screening_status": "cleared",
    "status": "reserved",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1015",
    "blood_group": "O-",
    "rh_type": "Negative",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 14,
    "screening_status": "cleared",
    "status": "used",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1016",
    "blood_group": "O-",
    "rh_type": "Negative",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -2,
    "exp_offset": 10,
    "screening_status": "pending",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1017",
    "blood_group": "O-",
    "rh_type": "Negative",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -30,
    "exp_offset": 1,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1018",
    "blood_group": "O-",
    "rh_type": "Negative",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -30,
    "exp_offset": 3,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1019",
    "blood_group": "O-",
    "rh_type": "Negative",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 5,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1020",
    "blood_group": "O-",
    "rh_type": "Negative",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -25,
    "exp_offset": 7,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1021",
    "blood_group": "O-",
    "rh_type": "Negative",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -20,
    "exp_offset": 9,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1022",
    "blood_group": "O-",
    "rh_type": "Negative",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 12,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1023",
    "blood_group": "O-",
    "rh_type": "Negative",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -10,
    "exp_offset": 18,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1024",
    "blood_group": "O-",
    "rh_type": "Negative",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -10,
    "exp_offset": 26,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1025",
    "blood_group": "A+",
    "rh_type": "Positive",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -35,
    "exp_offset": -5,
    "screening_status": "cleared",
    "status": "expired",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1026",
    "blood_group": "A+",
    "rh_type": "Positive",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 6,
    "screening_status": "cleared",
    "status": "reserved",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1027",
    "blood_group": "A+",
    "rh_type": "Positive",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 14,
    "screening_status": "cleared",
    "status": "used",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1028",
    "blood_group": "A+",
    "rh_type": "Positive",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -2,
    "exp_offset": 10,
    "screening_status": "pending",
    "status": "available",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1029",
    "blood_group": "A+",
    "rh_type": "Positive",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -30,
    "exp_offset": 1,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1030",
    "blood_group": "A+",
    "rh_type": "Positive",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -30,
    "exp_offset": 3,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1031",
    "blood_group": "A+",
    "rh_type": "Positive",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 5,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1032",
    "blood_group": "A+",
    "rh_type": "Positive",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -25,
    "exp_offset": 7,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1033",
    "blood_group": "A+",
    "rh_type": "Positive",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -20,
    "exp_offset": 9,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1034",
    "blood_group": "A+",
    "rh_type": "Positive",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 12,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1035",
    "blood_group": "A+",
    "rh_type": "Positive",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -10,
    "exp_offset": 18,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1036",
    "blood_group": "A+",
    "rh_type": "Positive",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -10,
    "exp_offset": 26,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1037",
    "blood_group": "A-",
    "rh_type": "Negative",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -35,
    "exp_offset": -5,
    "screening_status": "cleared",
    "status": "expired",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1038",
    "blood_group": "A-",
    "rh_type": "Negative",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 6,
    "screening_status": "cleared",
    "status": "reserved",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1039",
    "blood_group": "A-",
    "rh_type": "Negative",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 14,
    "screening_status": "cleared",
    "status": "used",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1040",
    "blood_group": "A-",
    "rh_type": "Negative",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -2,
    "exp_offset": 10,
    "screening_status": "pending",
    "status": "available",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1041",
    "blood_group": "A-",
    "rh_type": "Negative",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -30,
    "exp_offset": 1,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1042",
    "blood_group": "A-",
    "rh_type": "Negative",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -30,
    "exp_offset": 3,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1043",
    "blood_group": "A-",
    "rh_type": "Negative",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 5,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1044",
    "blood_group": "A-",
    "rh_type": "Negative",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -25,
    "exp_offset": 7,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1045",
    "blood_group": "A-",
    "rh_type": "Negative",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -20,
    "exp_offset": 9,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1046",
    "blood_group": "A-",
    "rh_type": "Negative",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 12,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1047",
    "blood_group": "A-",
    "rh_type": "Negative",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -10,
    "exp_offset": 18,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1048",
    "blood_group": "A-",
    "rh_type": "Negative",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -10,
    "exp_offset": 26,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1049",
    "blood_group": "B+",
    "rh_type": "Positive",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -35,
    "exp_offset": -5,
    "screening_status": "cleared",
    "status": "expired",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1050",
    "blood_group": "B+",
    "rh_type": "Positive",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 6,
    "screening_status": "cleared",
    "status": "reserved",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1051",
    "blood_group": "B+",
    "rh_type": "Positive",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 14,
    "screening_status": "cleared",
    "status": "used",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1052",
    "blood_group": "B+",
    "rh_type": "Positive",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -2,
    "exp_offset": 10,
    "screening_status": "pending",
    "status": "available",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1053",
    "blood_group": "B+",
    "rh_type": "Positive",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -30,
    "exp_offset": 1,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1054",
    "blood_group": "B+",
    "rh_type": "Positive",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -30,
    "exp_offset": 3,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1055",
    "blood_group": "B+",
    "rh_type": "Positive",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 5,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1056",
    "blood_group": "B+",
    "rh_type": "Positive",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -25,
    "exp_offset": 7,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1057",
    "blood_group": "B+",
    "rh_type": "Positive",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -20,
    "exp_offset": 9,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1058",
    "blood_group": "B+",
    "rh_type": "Positive",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 12,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1059",
    "blood_group": "B+",
    "rh_type": "Positive",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -10,
    "exp_offset": 18,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1060",
    "blood_group": "B+",
    "rh_type": "Positive",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -10,
    "exp_offset": 26,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1061",
    "blood_group": "B-",
    "rh_type": "Negative",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -35,
    "exp_offset": -5,
    "screening_status": "cleared",
    "status": "expired",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1062",
    "blood_group": "B-",
    "rh_type": "Negative",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 6,
    "screening_status": "cleared",
    "status": "reserved",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1063",
    "blood_group": "B-",
    "rh_type": "Negative",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 14,
    "screening_status": "cleared",
    "status": "used",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1064",
    "blood_group": "B-",
    "rh_type": "Negative",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -2,
    "exp_offset": 10,
    "screening_status": "pending",
    "status": "available",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1065",
    "blood_group": "B-",
    "rh_type": "Negative",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -30,
    "exp_offset": 1,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1066",
    "blood_group": "B-",
    "rh_type": "Negative",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -30,
    "exp_offset": 3,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1067",
    "blood_group": "B-",
    "rh_type": "Negative",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 5,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1068",
    "blood_group": "B-",
    "rh_type": "Negative",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -25,
    "exp_offset": 7,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1069",
    "blood_group": "B-",
    "rh_type": "Negative",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -20,
    "exp_offset": 9,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1070",
    "blood_group": "B-",
    "rh_type": "Negative",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 12,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1071",
    "blood_group": "B-",
    "rh_type": "Negative",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -10,
    "exp_offset": 18,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1072",
    "blood_group": "B-",
    "rh_type": "Negative",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -10,
    "exp_offset": 26,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1073",
    "blood_group": "AB+",
    "rh_type": "Positive",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -35,
    "exp_offset": -5,
    "screening_status": "cleared",
    "status": "expired",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1074",
    "blood_group": "AB+",
    "rh_type": "Positive",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 6,
    "screening_status": "cleared",
    "status": "reserved",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1075",
    "blood_group": "AB+",
    "rh_type": "Positive",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 14,
    "screening_status": "cleared",
    "status": "used",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1076",
    "blood_group": "AB+",
    "rh_type": "Positive",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -2,
    "exp_offset": 10,
    "screening_status": "pending",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1077",
    "blood_group": "AB+",
    "rh_type": "Positive",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -30,
    "exp_offset": 1,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1078",
    "blood_group": "AB+",
    "rh_type": "Positive",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -30,
    "exp_offset": 3,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1079",
    "blood_group": "AB+",
    "rh_type": "Positive",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 5,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1080",
    "blood_group": "AB+",
    "rh_type": "Positive",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -25,
    "exp_offset": 7,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1081",
    "blood_group": "AB+",
    "rh_type": "Positive",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -20,
    "exp_offset": 9,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1082",
    "blood_group": "AB+",
    "rh_type": "Positive",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 12,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1083",
    "blood_group": "AB+",
    "rh_type": "Positive",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -10,
    "exp_offset": 18,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1084",
    "blood_group": "AB+",
    "rh_type": "Positive",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -10,
    "exp_offset": 26,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1085",
    "blood_group": "AB-",
    "rh_type": "Negative",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -35,
    "exp_offset": -5,
    "screening_status": "cleared",
    "status": "expired",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1086",
    "blood_group": "AB-",
    "rh_type": "Negative",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 6,
    "screening_status": "cleared",
    "status": "reserved",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1087",
    "blood_group": "AB-",
    "rh_type": "Negative",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 14,
    "screening_status": "cleared",
    "status": "used",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1088",
    "blood_group": "AB-",
    "rh_type": "Negative",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -2,
    "exp_offset": 10,
    "screening_status": "pending",
    "status": "available",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1089",
    "blood_group": "AB-",
    "rh_type": "Negative",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -30,
    "exp_offset": 1,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1090",
    "blood_group": "AB-",
    "rh_type": "Negative",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -30,
    "exp_offset": 3,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1091",
    "blood_group": "AB-",
    "rh_type": "Negative",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -25,
    "exp_offset": 5,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1092",
    "blood_group": "AB-",
    "rh_type": "Negative",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -25,
    "exp_offset": 7,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1093",
    "blood_group": "AB-",
    "rh_type": "Negative",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -20,
    "exp_offset": 9,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1094",
    "blood_group": "AB-",
    "rh_type": "Negative",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -20,
    "exp_offset": 12,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-005",
    "blood_bank_name": "Demo Blood Bank Greater Noida",
    "city": "Greater Noida",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1095",
    "blood_group": "AB-",
    "rh_type": "Negative",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -10,
    "exp_offset": 18,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Freezer A"
  },
  {
    "id": "BL-1096",
    "blood_group": "AB-",
    "rh_type": "Negative",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -10,
    "exp_offset": 26,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1097",
    "blood_group": "O+",
    "rh_type": "Positive",
    "component": "Packed Red Blood Cells",
    "quantity_ml": 350,
    "col_offset": -28,
    "exp_offset": 2,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-001",
    "blood_bank_name": "Demo Blood Bank Delhi",
    "city": "Delhi",
    "storage_location": "Refrigerator A"
  },
  {
    "id": "BL-1098",
    "blood_group": "O-",
    "rh_type": "Negative",
    "component": "Whole Blood",
    "quantity_ml": 450,
    "col_offset": -30,
    "exp_offset": 4,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-002",
    "blood_bank_name": "Demo Blood Bank Noida",
    "city": "Noida",
    "storage_location": "Refrigerator B"
  },
  {
    "id": "BL-1099",
    "blood_group": "A+",
    "rh_type": "Positive",
    "component": "Platelets",
    "quantity_ml": 250,
    "col_offset": -3,
    "exp_offset": 2,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-003",
    "blood_bank_name": "Demo Blood Bank Ghaziabad",
    "city": "Ghaziabad",
    "storage_location": "Storage C"
  },
  {
    "id": "BL-1100",
    "blood_group": "B+",
    "rh_type": "Positive",
    "component": "Fresh Frozen Plasma",
    "quantity_ml": 200,
    "col_offset": -60,
    "exp_offset": 28,
    "screening_status": "cleared",
    "status": "available",
    "blood_bank_id": "BB-004",
    "blood_bank_name": "Demo Blood Bank Faridabad",
    "city": "Faridabad",
    "storage_location": "Freezer A"
  }
];

export const INITIAL_100_BLOOD_INVENTORY: BloodInventoryUnit[] = rawRecords.map(r => ({
  id: r.id,
  blood_group: r.blood_group,
  rh_type: r.rh_type,
  component: r.component,
  quantity_ml: r.quantity_ml,
  collection_date: getRelativeDate(r.col_offset),
  expiration_date: getRelativeDate(r.exp_offset),
  screening_status: r.screening_status,
  status: r.status,
  blood_bank_id: r.blood_bank_id,
  blood_bank_name: r.blood_bank_name,
  city: r.city,
  storage_location: r.storage_location,
  created_at: new Date(Date.now() + r.col_offset * 86400000).toISOString()
}));
