from datetime import date, datetime, timedelta, timezone
from app.core.config import UserRole, BloodGroup, ComponentType, AvailabilityStatus
from app.core.database import SessionLocal, Base, engine
from app.core.security import get_password_hash
from app.models.user import User
from app.models.facility import BloodBank, Hospital
from app.models.inventory import BloodInventory
from app.models.donor import DonorProfile
from app.models.shelf_life import ComponentShelfLifeRule
from app.models.wastage import WastageRecord
from app.models.system_config import SystemConfiguration

VERIFIED_FACILITIES = [
    {
        "name": "AIIMS Main Blood Bank & Transfusion Medicine",
        "short_name": "AIIMS Blood Bank",
        "parent_hospital": "All India Institute of Medical Sciences",
        "license_number": "BB-DL-001",
        "district": "South Delhi",
        "state": "Delhi",
        "address": "Ansari Nagar, Sri Aurobindo Marg, New Delhi",
        "city": "New Delhi",
        "pincode": "110029",
        "region": "South Delhi",
        "category": "Government",
        "organization_type": "Government",
        "latitude": 28.5672,
        "longitude": 77.2100,
        "contact_number": "+91 11 26588500",
        "email": "bloodbank@aiims.edu",
        "website": "https://www.aiims.edu",
        "storage_capacity": 5000,
        "cold_chain_verified": True,
        "source_name": "Ministry of Health & Family Welfare / e-RaktKosh",
        "source_url": "https://eraktkosh.mohfw.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Indian Red Cross Society National HQ Blood Bank",
        "short_name": "Indian Red Cross Blood Bank",
        "parent_hospital": "Indian Red Cross Society",
        "license_number": "BB-DL-002",
        "district": "Central Delhi",
        "state": "Delhi",
        "address": "1, Red Cross Road, Sansad Marg Area, New Delhi",
        "city": "New Delhi",
        "pincode": "110001",
        "region": "Central Delhi",
        "category": "Red Cross",
        "organization_type": "Red Cross",
        "latitude": 28.6250,
        "longitude": 77.2183,
        "contact_number": "+91 11 23716441",
        "email": "bloodbank@indianredcross.org",
        "website": "https://www.indianredcross.org",
        "storage_capacity": 3000,
        "cold_chain_verified": True,
        "source_name": "Delhi State AIDS Control Society (DSACS)",
        "source_url": "https://dsacs.delhi.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Lok Nayak Hospital (LNJP) Blood Centre",
        "short_name": "LNJP Hospital Blood Centre",
        "parent_hospital": "Lok Nayak Jai Prakash Narayan Hospital",
        "license_number": "BB-DL-003",
        "district": "Central Delhi",
        "state": "Delhi",
        "address": "Jawaharlal Nehru Marg, Delhi Gate, New Delhi",
        "city": "New Delhi",
        "pincode": "110002",
        "region": "Central Delhi",
        "category": "Government",
        "organization_type": "Government",
        "latitude": 28.6369,
        "longitude": 77.2410,
        "contact_number": "+91 11 23236000",
        "email": "lnjphospital@delhi.gov.in",
        "website": "https://delhi.gov.in",
        "storage_capacity": 2500,
        "cold_chain_verified": True,
        "source_name": "Delhi State AIDS Control Society (DSACS)",
        "source_url": "https://dsacs.delhi.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Safdarjung Hospital Regional Blood Centre",
        "short_name": "Safdarjung Blood Centre",
        "parent_hospital": "Vardhman Mahavir Medical College & Safdarjung Hospital",
        "license_number": "BB-DL-004",
        "district": "South Delhi",
        "state": "Delhi",
        "address": "Ring Road, Opposite AIIMS, New Delhi",
        "city": "New Delhi",
        "pincode": "110029",
        "region": "South Delhi",
        "category": "Government",
        "organization_type": "Government",
        "latitude": 28.5701,
        "longitude": 77.2078,
        "contact_number": "+91 11 26165060",
        "email": "bloodbank@vmmc-sjh.nic.in",
        "website": "http://www.vmmc-sjh.nic.in",
        "storage_capacity": 2500,
        "cold_chain_verified": True,
        "source_name": "Ministry of Health & Family Welfare / e-RaktKosh",
        "source_url": "https://eraktkosh.mohfw.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Guru Teg Bahadur (GTB) Hospital Blood Centre",
        "short_name": "GTB Hospital Blood Centre",
        "parent_hospital": "Guru Teg Bahadur Hospital & UCMS",
        "license_number": "BB-DL-005",
        "district": "Shahdara",
        "state": "Delhi",
        "address": "Dilshad Garden, Taharpur Road, Delhi",
        "city": "Delhi",
        "pincode": "110095",
        "region": "Shahdara",
        "category": "Government",
        "organization_type": "Government",
        "latitude": 28.6865,
        "longitude": 77.3117,
        "contact_number": "+91 11 22586262",
        "email": "gtbh@delhi.gov.in",
        "website": "https://delhi.gov.in",
        "storage_capacity": 2200,
        "cold_chain_verified": True,
        "source_name": "Delhi State AIDS Control Society (DSACS)",
        "source_url": "https://dsacs.delhi.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Swami Dayanand Hospital Blood Bank",
        "short_name": "Swami Dayanand Blood Bank",
        "parent_hospital": "Swami Dayanand Hospital (MCD)",
        "license_number": "BB-DL-006",
        "district": "Shahdara",
        "state": "Delhi",
        "address": "Dilshad Garden, Near Telephone Exchange, Shahdara, Delhi",
        "city": "Delhi",
        "pincode": "110095",
        "region": "Shahdara",
        "category": "Government",
        "organization_type": "Government",
        "latitude": 28.6812,
        "longitude": 77.3190,
        "contact_number": "+91 11 22582046",
        "email": "sdnhospital@mcd.nic.in",
        "website": "https://mcdonline.nic.in",
        "storage_capacity": 1000,
        "cold_chain_verified": True,
        "source_name": "Delhi State AIDS Control Society (DSACS)",
        "source_url": "https://dsacs.delhi.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Hindu Rao Hospital Blood Centre",
        "short_name": "Hindu Rao Blood Centre",
        "parent_hospital": "Hindu Rao Hospital (MCD)",
        "license_number": "BB-DL-007",
        "district": "North Delhi",
        "state": "Delhi",
        "address": "Malka Ganj, Subzi Mandi, Delhi",
        "city": "Delhi",
        "pincode": "110007",
        "region": "North Delhi",
        "category": "Government",
        "organization_type": "Government",
        "latitude": 28.6755,
        "longitude": 77.2106,
        "contact_number": "+91 11 23919476",
        "email": "hrh-delhi@nic.in",
        "website": "https://mcdonline.nic.in",
        "storage_capacity": 1500,
        "cold_chain_verified": True,
        "source_name": "Delhi State AIDS Control Society (DSACS)",
        "source_url": "https://dsacs.delhi.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Dr. Baba Saheb Ambedkar Hospital Blood Centre",
        "short_name": "Dr. BSA Hospital Blood Centre",
        "parent_hospital": "Dr. BSA Hospital Rohini",
        "license_number": "BB-DL-008",
        "district": "North West Delhi",
        "state": "Delhi",
        "address": "Sector 6, Rohini, Delhi",
        "city": "Delhi",
        "pincode": "110085",
        "region": "North West Delhi",
        "category": "Government",
        "organization_type": "Government",
        "latitude": 28.7121,
        "longitude": 77.1147,
        "contact_number": "+91 11 27055585",
        "email": "bsahospital@delhi.gov.in",
        "website": "https://delhi.gov.in",
        "storage_capacity": 1800,
        "cold_chain_verified": True,
        "source_name": "Delhi State AIDS Control Society (DSACS)",
        "source_url": "https://dsacs.delhi.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Rajiv Gandhi Cancer Institute Blood Bank",
        "short_name": "RGCI Blood Bank",
        "parent_hospital": "Rajiv Gandhi Cancer Institute & Research Centre",
        "license_number": "BB-DL-009",
        "district": "North West Delhi",
        "state": "Delhi",
        "address": "Sector 5, Rohini, Delhi",
        "city": "Delhi",
        "pincode": "110085",
        "region": "North West Delhi",
        "category": "Charitable Trust",
        "organization_type": "Charitable Trust",
        "latitude": 28.7186,
        "longitude": 77.1089,
        "contact_number": "+91 11 47022222",
        "email": "bloodbank@rgcirc.org",
        "website": "https://www.rgcirc.org",
        "storage_capacity": 1200,
        "cold_chain_verified": True,
        "source_name": "e-RaktKosh / DSACS",
        "source_url": "https://eraktkosh.mohfw.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "St. Stephen's Hospital Blood Centre",
        "short_name": "St. Stephen's Blood Centre",
        "parent_hospital": "St. Stephen's Hospital",
        "license_number": "BB-DL-010",
        "district": "North Delhi",
        "state": "Delhi",
        "address": "Tis Hazari, Near Kashmere Gate, Delhi",
        "city": "Delhi",
        "pincode": "110054",
        "region": "North Delhi",
        "category": "Charitable Trust",
        "organization_type": "Charitable Trust",
        "latitude": 28.6669,
        "longitude": 77.2188,
        "contact_number": "+91 11 23966021",
        "email": "bloodbank@ststephenshospital.org",
        "website": "https://www.ststephenshospital.org",
        "storage_capacity": 1400,
        "cold_chain_verified": True,
        "source_name": "Delhi State AIDS Control Society (DSACS)",
        "source_url": "https://dsacs.delhi.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Sant Parmanand Hospital Blood Centre",
        "short_name": "Sant Parmanand Blood Centre",
        "parent_hospital": "Sant Parmanand Hospital",
        "license_number": "BB-DL-011",
        "district": "North Delhi",
        "state": "Delhi",
        "address": "18, Alipur Road, Civil Lines, Delhi",
        "city": "Delhi",
        "pincode": "110054",
        "region": "North Delhi",
        "category": "Charitable Trust",
        "organization_type": "Charitable Trust",
        "latitude": 28.6798,
        "longitude": 77.2251,
        "contact_number": "+91 11 23981260",
        "email": "bloodbank@sphdelhi.org",
        "website": "https://www.sphdelhi.org",
        "storage_capacity": 1100,
        "cold_chain_verified": True,
        "source_name": "Delhi State AIDS Control Society (DSACS)",
        "source_url": "https://dsacs.delhi.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Deen Dayal Upadhyaya (DDU) Hospital Blood Centre",
        "short_name": "DDU Hospital Blood Centre",
        "parent_hospital": "Deen Dayal Upadhyaya Hospital",
        "license_number": "BB-DL-012",
        "district": "West Delhi",
        "state": "Delhi",
        "address": "Clock Tower, Hari Nagar, New Delhi",
        "city": "New Delhi",
        "pincode": "110064",
        "region": "West Delhi",
        "category": "Government",
        "organization_type": "Government",
        "latitude": 28.6284,
        "longitude": 77.1062,
        "contact_number": "+91 11 25494402",
        "email": "dduhospital@delhi.gov.in",
        "website": "https://delhi.gov.in",
        "storage_capacity": 1600,
        "cold_chain_verified": True,
        "source_name": "Delhi State AIDS Control Society (DSACS)",
        "source_url": "https://dsacs.delhi.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "ESI Hospital Blood Bank (Basaidarapur)",
        "short_name": "ESIC Basaidarapur Blood Bank",
        "parent_hospital": "ESI-PGIMSR & Model Hospital Basaidarapur",
        "license_number": "BB-DL-013",
        "district": "West Delhi",
        "state": "Delhi",
        "address": "Ring Road, Basaidarapur, New Delhi",
        "city": "New Delhi",
        "pincode": "110015",
        "region": "West Delhi",
        "category": "Government",
        "organization_type": "Government",
        "latitude": 28.6575,
        "longitude": 77.1350,
        "contact_number": "+91 11 25100664",
        "email": "ms-basai.dl@esic.nic.in",
        "website": "https://www.esic.nic.in",
        "storage_capacity": 1200,
        "cold_chain_verified": True,
        "source_name": "Delhi State AIDS Control Society (DSACS)",
        "source_url": "https://dsacs.delhi.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Mata Chanan Devi Hospital Blood Centre",
        "short_name": "Mata Chanan Devi Blood Centre",
        "parent_hospital": "Mata Chanan Devi Hospital",
        "license_number": "BB-DL-014",
        "district": "West Delhi",
        "state": "Delhi",
        "address": "C-1, Janakpuri, New Delhi",
        "city": "New Delhi",
        "pincode": "110058",
        "region": "West Delhi",
        "category": "Charitable Trust",
        "organization_type": "Charitable Trust",
        "latitude": 28.6214,
        "longitude": 77.0865,
        "contact_number": "+91 11 45582000",
        "email": "bloodbank@mcdh.in",
        "website": "https://www.mcdh.in",
        "storage_capacity": 1100,
        "cold_chain_verified": True,
        "source_name": "Delhi State AIDS Control Society (DSACS)",
        "source_url": "https://dsacs.delhi.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Sri Balaji Action Medical Institute Blood Centre",
        "short_name": "Action Balaji Blood Centre",
        "parent_hospital": "Sri Balaji Action Medical Institute",
        "license_number": "BB-DL-015",
        "district": "West Delhi",
        "state": "Delhi",
        "address": "FC-34, A-4, Paschim Vihar, New Delhi",
        "city": "New Delhi",
        "pincode": "110063",
        "region": "West Delhi",
        "category": "Private",
        "organization_type": "Private",
        "latitude": 28.6698,
        "longitude": 77.1084,
        "contact_number": "+91 11 42888888",
        "email": "bloodbank@actionhospital.in",
        "website": "https://www.actionhospital.in",
        "storage_capacity": 1300,
        "cold_chain_verified": True,
        "source_name": "e-RaktKosh / DSACS",
        "source_url": "https://eraktkosh.mohfw.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Rotary Blood Bank Delhi",
        "short_name": "Rotary Blood Bank",
        "parent_hospital": "Rotary Blood Bank Society",
        "license_number": "BB-DL-016",
        "district": "South East Delhi",
        "state": "Delhi",
        "address": "56-57, Tughlakabad Institutional Area, New Delhi",
        "city": "New Delhi",
        "pincode": "110062",
        "region": "South East Delhi",
        "category": "Charitable Trust",
        "organization_type": "Charitable Trust",
        "latitude": 28.5133,
        "longitude": 77.2625,
        "contact_number": "+91 11 29967666",
        "email": "info@rotarybloodbank.org",
        "website": "https://www.rotarybloodbank.org",
        "storage_capacity": 2500,
        "cold_chain_verified": True,
        "source_name": "Delhi State AIDS Control Society (DSACS)",
        "source_url": "https://dsacs.delhi.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Holy Family Hospital Blood Centre",
        "short_name": "Holy Family Blood Centre",
        "parent_hospital": "Holy Family Hospital",
        "license_number": "BB-DL-017",
        "district": "South East Delhi",
        "state": "Delhi",
        "address": "Okhla Road, Jamia Nagar, Okhla, New Delhi",
        "city": "New Delhi",
        "pincode": "110025",
        "region": "South East Delhi",
        "category": "Charitable Trust",
        "organization_type": "Charitable Trust",
        "latitude": 28.5630,
        "longitude": 77.2764,
        "contact_number": "+91 11 26845900",
        "email": "bloodbank@holyfamilyhospitaldelhi.org",
        "website": "https://www.holyfamilyhospitaldelhi.org",
        "storage_capacity": 1500,
        "cold_chain_verified": True,
        "source_name": "Delhi State AIDS Control Society (DSACS)",
        "source_url": "https://dsacs.delhi.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Indraprastha Apollo Hospital Blood Centre",
        "short_name": "Apollo Blood Centre",
        "parent_hospital": "Indraprastha Apollo Hospitals",
        "license_number": "BB-DL-018",
        "district": "South East Delhi",
        "state": "Delhi",
        "address": "Delhi-Mathura Road, Sarita Vihar, New Delhi",
        "city": "New Delhi",
        "pincode": "110076",
        "region": "South East Delhi",
        "category": "Private",
        "organization_type": "Private",
        "latitude": 28.5414,
        "longitude": 77.2831,
        "contact_number": "+91 11 26925858",
        "email": "bloodbank_delhi@apollohospitals.com",
        "website": "https://delhi.apollohospitals.com",
        "storage_capacity": 2000,
        "cold_chain_verified": True,
        "source_name": "e-RaktKosh / DSACS",
        "source_url": "https://eraktkosh.mohfw.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Moolchand Hospital Blood Centre",
        "short_name": "Moolchand Blood Centre",
        "parent_hospital": "Moolchand Medcity",
        "license_number": "BB-DL-019",
        "district": "South Delhi",
        "state": "Delhi",
        "address": "Lala Lajpat Rai Marg, Defence Colony, New Delhi",
        "city": "New Delhi",
        "pincode": "110024",
        "region": "South Delhi",
        "category": "Private",
        "organization_type": "Private",
        "latitude": 28.5662,
        "longitude": 77.2346,
        "contact_number": "+91 11 42000000",
        "email": "bloodbank@moolchandhealthcare.com",
        "website": "https://www.moolchandhealthcare.com",
        "storage_capacity": 1000,
        "cold_chain_verified": True,
        "source_name": "Delhi State AIDS Control Society (DSACS)",
        "source_url": "https://dsacs.delhi.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Noida District Combined Hospital Blood Bank",
        "short_name": "Noida District Blood Bank",
        "parent_hospital": "District Combined Hospital Sector-39",
        "license_number": "BB-UP-001",
        "district": "Gautam Buddha Nagar",
        "state": "Uttar Pradesh",
        "address": "Sector 39, Noida, Gautam Buddha Nagar",
        "city": "Noida",
        "pincode": "201301",
        "region": "NCR / Gautam Buddha Nagar",
        "category": "Government",
        "organization_type": "Government",
        "latitude": 28.5708,
        "longitude": 77.3489,
        "contact_number": "+91 120 2456789",
        "email": "dchnoida@up.gov.in",
        "website": "http://uphealth.up.nic.in",
        "storage_capacity": 1200,
        "cold_chain_verified": True,
        "source_name": "e-RaktKosh / UP State Blood Transfusion Council",
        "source_url": "https://eraktkosh.mohfw.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Government Institute of Medical Sciences (GIMS) Blood Centre",
        "short_name": "GIMS Blood Centre",
        "parent_hospital": "Government Institute of Medical Sciences",
        "license_number": "BB-UP-002",
        "district": "Gautam Buddha Nagar",
        "state": "Uttar Pradesh",
        "address": "Greater Noida, Gautam Buddha Nagar",
        "city": "Greater Noida",
        "pincode": "201310",
        "region": "NCR / Greater Noida",
        "category": "Government",
        "organization_type": "Government",
        "latitude": 28.4682,
        "longitude": 77.5040,
        "contact_number": "+91 120 2341738",
        "email": "bloodbank@gims.ac.in",
        "website": "https://gims.ac.in",
        "storage_capacity": 1000,
        "cold_chain_verified": True,
        "source_name": "e-RaktKosh / UP State Blood Transfusion Council",
        "source_url": "https://eraktkosh.mohfw.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "MMG District Hospital Blood Bank",
        "short_name": "MMG Hospital Blood Bank",
        "parent_hospital": "Mahanand Mission Gaushala (MMG) District Hospital",
        "license_number": "BB-UP-003",
        "district": "Ghaziabad",
        "state": "Uttar Pradesh",
        "address": "GT Road, Near Model Town, Ghaziabad",
        "city": "Ghaziabad",
        "pincode": "201001",
        "region": "NCR / Ghaziabad",
        "category": "Government",
        "organization_type": "Government",
        "latitude": 28.6692,
        "longitude": 77.4338,
        "contact_number": "+91 120 2730102",
        "email": "mmghospital@up.gov.in",
        "website": "http://uphealth.up.nic.in",
        "storage_capacity": 900,
        "cold_chain_verified": True,
        "source_name": "e-RaktKosh / UP State Blood Transfusion Council",
        "source_url": "https://eraktkosh.mohfw.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Civil Hospital Blood Centre Gurugram",
        "short_name": "Gurugram Civil Blood Centre",
        "parent_hospital": "Civil Hospital Sector-10A",
        "license_number": "BB-HR-001",
        "district": "Gurugram",
        "state": "Haryana",
        "address": "Sector 10A, Near Hero Honda Chowk, Gurugram",
        "city": "Gurugram",
        "pincode": "122001",
        "region": "NCR / Gurugram",
        "category": "Government",
        "organization_type": "Government",
        "latitude": 28.4595,
        "longitude": 77.0266,
        "contact_number": "+91 124 2320102",
        "email": "civilhospitalggn@hry.nic.in",
        "website": "https://haryanahealth.gov.in",
        "storage_capacity": 1000,
        "cold_chain_verified": True,
        "source_name": "e-RaktKosh / Haryana Health Department",
        "source_url": "https://eraktkosh.mohfw.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
    {
        "name": "Badshah Khan (BK) Civil Hospital Blood Bank",
        "short_name": "BK Hospital Blood Bank",
        "parent_hospital": "BK Civil Hospital NIT Faridabad",
        "license_number": "BB-HR-002",
        "district": "Faridabad",
        "state": "Haryana",
        "address": "NIT-3, Near BK Chowk, Faridabad",
        "city": "Faridabad",
        "pincode": "121001",
        "region": "NCR / Faridabad",
        "category": "Government",
        "organization_type": "Government",
        "latitude": 28.3964,
        "longitude": 77.3012,
        "contact_number": "+91 129 2415102",
        "email": "bkhospitalfbd@hry.nic.in",
        "website": "https://haryanahealth.gov.in",
        "storage_capacity": 850,
        "cold_chain_verified": True,
        "source_name": "e-RaktKosh / Haryana Health Department",
        "source_url": "https://eraktkosh.mohfw.gov.in/",
        "source_type": "Government Official",
        "source_verified": True,
        "last_verified_at": "2026-03-01T00:00:00Z",
        "data_status": "VERIFIED",
        "is_active": True,
    },
]


def calculate_expiry_risk(days: int) -> str:
    """Standard FEFO risk tiering."""
    if days <= 2:
        return "CRITICAL"
    elif days <= 5:
        return "HIGH"
    elif days <= 10:
        return "MEDIUM"
    return "LOW"


def seed_database():
    """Seed comprehensive verified facilities and simulated demo inventory."""
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    today = date.today()
    now = datetime.now(timezone.utc)

    try:
        print("1. Seeding Verified Blood Centres...")
        # Upsert or seed all 24 verified facilities
        existing_banks = {b.license_number: b for b in db.query(BloodBank).all()}
        for data in VERIFIED_FACILITIES:
            lic = data["license_number"]
            if lic in existing_banks:
                bank = existing_banks[lic]
                for k, v in data.items():
                    setattr(bank, k, v)
            else:
                bank = BloodBank(**data)
                db.add(bank)
        db.commit()

        # Seed Hospitals
        if db.query(Hospital).count() == 0:
            hospitals = [
                Hospital(
                    name="AIIMS Apex Trauma Center",
                    license_number="HOSP-DL-001",
                    district="South Delhi",
                    state="Delhi",
                    latitude=28.5672,
                    longitude=77.2100,
                    contact_number="+91 11 26588500",
                    has_trauma_center=True,
                    bed_capacity=1200,
                    is_active=True,
                ),
                Hospital(
                    name="Lok Nayak Jai Prakash Narayan Hospital",
                    license_number="HOSP-DL-002",
                    district="Central Delhi",
                    state="Delhi",
                    latitude=28.6369,
                    longitude=77.2410,
                    contact_number="+91 11 23236000",
                    has_trauma_center=True,
                    bed_capacity=2000,
                    is_active=True,
                ),
                Hospital(
                    name="Fortis Memorial Research Institute",
                    license_number="HOSP-HR-001",
                    district="Gurugram",
                    state="Haryana",
                    latitude=28.4554,
                    longitude=77.0722,
                    contact_number="+91 124 4962200",
                    has_trauma_center=False,
                    bed_capacity=450,
                    is_active=True,
                ),
            ]
            db.add_all(hospitals)
            db.commit()

        # Seed Users across roles
        demo_users = [
            {
                "email": "admin@smartblood.gov",
                "password": "AdminPassword123!",
                "full_name": "Dr. Rajesh Verma (Regional Director)",
                "role": UserRole.ADMIN,
                "phone_masked": "+91 ******8890",
            },
            {
                "email": "bloodbank@redcross.org",
                "password": "BankPassword123!",
                "full_name": "Sunita Rao (Lead Transfusionist)",
                "role": UserRole.BLOOD_BANK,
                "facility_type": "BLOOD_BANK",
                "facility_id": 1,
                "phone_masked": "+91 ******4412",
            },
            {
                "email": "trauma@aiims.edu",
                "password": "HospitalPassword123!",
                "full_name": "Dr. Vikram Sethi (Trauma Chief)",
                "role": UserRole.HOSPITAL,
                "facility_type": "HOSPITAL",
                "facility_id": 1,
                "phone_masked": "+91 ******6621",
            },
            {
                "email": "donor.priya@example.com",
                "password": "DonorPassword123!",
                "full_name": "Priya Nair",
                "role": UserRole.DONOR,
                "phone_masked": "+91 ******2314",
            },
            {
                "email": "patient.rahul@example.com",
                "password": "PatientPassword123!",
                "full_name": "Rahul Mehra",
                "role": UserRole.PATIENT,
                "phone_masked": "+91 ******9981",
            },
        ]

        for u in demo_users:
            if not db.query(User).filter(User.email == u["email"]).first():
                user_obj = User(
                    email=u["email"],
                    hashed_password=get_password_hash(u["password"]),
                    full_name=u["full_name"],
                    role=u["role"],
                    phone_masked=u["phone_masked"],
                    facility_type=u.get("facility_type"),
                    facility_id=u.get("facility_id"),
                    is_active=True,
                )
                db.add(user_obj)
                db.commit()
                db.refresh(user_obj)

                if u["role"] == UserRole.DONOR:
                    donor = DonorProfile(
                        user_id=user_obj.id,
                        blood_group="O+",
                        last_donation_date=today - timedelta(days=95),
                        is_eligible=True,
                        total_donations=4,
                        public_donor_tag=f"DONOR-DL-{user_obj.id:04d}",
                        emergency_donor_opt_in=True,
                        preferred_district="Central Delhi",
                    )
                    db.add(donor)
                    db.commit()

        # Seed Simulated Inventory for ALL 24 Blood Centres
        print("2. Seeding Realistic Demo Simulated Inventory across 24 Centres...")
        db.query(BloodInventory).delete()

        all_banks = db.query(BloodBank).all()
        inventory_items = []

        # Archetype patterns to simulate realistic variability
        # Component types: PRBC, PLATELETS, FFP, WHOLE_BLOOD
        blood_groups = [
            BloodGroup.O_POS, BloodGroup.O_NEG,
            BloodGroup.A_POS, BloodGroup.A_NEG,
            BloodGroup.B_POS, BloodGroup.B_NEG,
            BloodGroup.AB_POS, BloodGroup.AB_NEG,
        ]

        for idx, b in enumerate(all_banks):
            b_id = b.id
            # Seed PRBC units across major groups
            # O+
            units = 15 + ((idx * 7) % 20)
            days = 15 + ((idx * 3) % 25)
            inventory_items.append(BloodInventory(
                facility_id=b_id,
                blood_group=BloodGroup.O_POS,
                component=ComponentType.PRBC,
                units_available=units,
                batch_number=f"PRBC-OPOS-{b_id}-101",
                status=AvailabilityStatus.CONFIRMED,
                collected_date=today - timedelta(days=42 - days),
                expiry_date=today + timedelta(days=days),
                temperature_celsius=4.0,
                source_tag="DIRECT_LAB_VERIFIED",
                inventory_status="DEMO_SIMULATED",
                demo_notice="Simulated data for demonstration only",
                critical_threshold=5,
                days_to_expiry=days,
                expiry_risk=calculate_expiry_risk(days),
                stock_source="e-RaktKosh Schema Demo Simulation",
                stock_source_url="https://eraktkosh.mohfw.gov.in/",
                stock_last_updated=now,
            ))

            # O- (Rare universal donor - often critical shortage)
            units_oneg = 2 if idx % 3 == 0 else (4 + (idx % 5))
            days_oneg = 4 if idx % 4 == 0 else (8 + ((idx * 5) % 20))
            inventory_items.append(BloodInventory(
                facility_id=b_id,
                blood_group=BloodGroup.O_NEG,
                component=ComponentType.PRBC,
                units_available=units_oneg,
                batch_number=f"PRBC-ONEG-{b_id}-102",
                status=AvailabilityStatus.CONFIRMED,
                collected_date=today - timedelta(days=42 - days_oneg),
                expiry_date=today + timedelta(days=days_oneg),
                temperature_celsius=3.8,
                source_tag="DIRECT_LAB_VERIFIED",
                inventory_status="DEMO_SIMULATED",
                demo_notice="Simulated data for demonstration only",
                critical_threshold=5,
                days_to_expiry=days_oneg,
                expiry_risk=calculate_expiry_risk(days_oneg),
                stock_source="e-RaktKosh Schema Demo Simulation",
                stock_source_url="https://eraktkosh.mohfw.gov.in/",
                stock_last_updated=now,
            ))

            # A+
            units_apos = 10 + ((idx * 4) % 18)
            days_apos = 12 + ((idx * 2) % 22)
            inventory_items.append(BloodInventory(
                facility_id=b_id,
                blood_group=BloodGroup.A_POS,
                component=ComponentType.PRBC,
                units_available=units_apos,
                batch_number=f"PRBC-APOS-{b_id}-103",
                status=AvailabilityStatus.CONFIRMED,
                collected_date=today - timedelta(days=42 - days_apos),
                expiry_date=today + timedelta(days=days_apos),
                temperature_celsius=4.1,
                source_tag="DIRECT_LAB_VERIFIED",
                inventory_status="DEMO_SIMULATED",
                demo_notice="Simulated data for demonstration only",
                critical_threshold=5,
                days_to_expiry=days_apos,
                expiry_risk=calculate_expiry_risk(days_apos),
                stock_source="e-RaktKosh Schema Demo Simulation",
                stock_source_url="https://eraktkosh.mohfw.gov.in/",
                stock_last_updated=now,
            ))

            # B+
            units_bpos = 14 + ((idx * 5) % 22)
            days_bpos = 18 + ((idx * 4) % 18)
            inventory_items.append(BloodInventory(
                facility_id=b_id,
                blood_group=BloodGroup.B_POS,
                component=ComponentType.PRBC,
                units_available=units_bpos,
                batch_number=f"PRBC-BPOS-{b_id}-104",
                status=AvailabilityStatus.CONFIRMED,
                collected_date=today - timedelta(days=42 - days_bpos),
                expiry_date=today + timedelta(days=days_bpos),
                temperature_celsius=4.2,
                source_tag="DIRECT_LAB_VERIFIED",
                inventory_status="DEMO_SIMULATED",
                demo_notice="Simulated data for demonstration only",
                critical_threshold=5,
                days_to_expiry=days_bpos,
                expiry_risk=calculate_expiry_risk(days_bpos),
                stock_source="e-RaktKosh Schema Demo Simulation",
                stock_source_url="https://eraktkosh.mohfw.gov.in/",
                stock_last_updated=now,
            ))

            # Platelets (short 5-day shelf life! Demonstrates FEFO urgency)
            # Alternate some with 1-2 days remaining (CRITICAL) and some with 3-4 days (HIGH/MEDIUM)
            plt_days = 1 if (idx % 2 == 0) else (3 if (idx % 3 == 0) else 4)
            plt_units = 3 + (idx % 8)
            inventory_items.append(BloodInventory(
                facility_id=b_id,
                blood_group=BloodGroup.A_POS if idx % 2 == 0 else BloodGroup.O_POS,
                component=ComponentType.PLATELETS,
                units_available=plt_units,
                batch_number=f"PLT-DEMO-{b_id}-201",
                status=AvailabilityStatus.CONFIRMED,
                collected_date=today - timedelta(days=5 - plt_days),
                expiry_date=today + timedelta(days=plt_days),
                temperature_celsius=22.0,
                source_tag="DIRECT_LAB_VERIFIED",
                inventory_status="DEMO_SIMULATED",
                demo_notice="Simulated data for demonstration only",
                critical_threshold=4,
                days_to_expiry=plt_days,
                expiry_risk=calculate_expiry_risk(plt_days),
                stock_source="e-RaktKosh Schema Demo Simulation",
                stock_source_url="https://eraktkosh.mohfw.gov.in/",
                stock_last_updated=now,
            ))

            # FFP (Fresh Frozen Plasma - long shelf life: 365 days)
            ffp_units = 18 + ((idx * 6) % 25)
            ffp_days = 180 + ((idx * 15) % 150)
            inventory_items.append(BloodInventory(
                facility_id=b_id,
                blood_group=BloodGroup.AB_POS if idx % 2 == 0 else BloodGroup.B_POS,
                component=ComponentType.FFP,
                units_available=ffp_units,
                batch_number=f"FFP-DEMO-{b_id}-301",
                status=AvailabilityStatus.CONFIRMED,
                collected_date=today - timedelta(days=365 - ffp_days),
                expiry_date=today + timedelta(days=ffp_days),
                temperature_celsius=-22.0,
                source_tag="DIRECT_LAB_VERIFIED",
                inventory_status="DEMO_SIMULATED",
                demo_notice="Simulated data for demonstration only",
                critical_threshold=5,
                days_to_expiry=ffp_days,
                expiry_risk=calculate_expiry_risk(ffp_days),
                stock_source="e-RaktKosh Schema Demo Simulation",
                stock_source_url="https://eraktkosh.mohfw.gov.in/",
                stock_last_updated=now,
            ))

            # Whole Blood
            wb_units = 5 + (idx % 12)
            wb_days = 10 + (idx % 20)
            inventory_items.append(BloodInventory(
                facility_id=b_id,
                blood_group=BloodGroup.AB_NEG if idx % 2 == 0 else BloodGroup.B_NEG,
                component=ComponentType.WHOLE_BLOOD,
                units_available=wb_units,
                batch_number=f"WB-DEMO-{b_id}-401",
                status=AvailabilityStatus.CONFIRMED,
                collected_date=today - timedelta(days=35 - wb_days),
                expiry_date=today + timedelta(days=wb_days),
                temperature_celsius=4.0,
                source_tag="DIRECT_LAB_VERIFIED",
                inventory_status="DEMO_SIMULATED",
                demo_notice="Simulated data for demonstration only",
                critical_threshold=3,
                days_to_expiry=wb_days,
                expiry_risk=calculate_expiry_risk(wb_days),
                stock_source="e-RaktKosh Schema Demo Simulation",
                stock_source_url="https://eraktkosh.mohfw.gov.in/",
                stock_last_updated=now,
            ))

        db.add_all(inventory_items)
        db.commit()

        # Seed Shelf Life Rules
        if db.query(ComponentShelfLifeRule).count() == 0:
            rules = [
                ComponentShelfLifeRule(
                    component="PRBC",
                    storage_method="2°C to 6°C in specialized blood bank refrigerator with continuous temperature logging",
                    shelf_life_value=42,
                    shelf_life_unit="DAYS",
                    regulatory_reference="DGHS / NACO Technical Manual 3rd Edition; CPDA-1/SAGM anticoagulant solution",
                    active=True,
                ),
                ComponentShelfLifeRule(
                    component="PLATELETS",
                    storage_method="20°C to 24°C in platelet incubator with continuous horizontal agitation (60 RPM)",
                    shelf_life_value=5,
                    shelf_life_unit="DAYS",
                    regulatory_reference="DGHS Standards for Blood Banks and Transfusion Services; AABB Standards",
                    active=True,
                ),
                ComponentShelfLifeRule(
                    component="FFP",
                    storage_method="Deep frozen at -18°C or colder in plasma ultra-low freezer",
                    shelf_life_value=365,
                    shelf_life_unit="DAYS",
                    regulatory_reference="DGHS National Blood Policy Guidelines; CDSCO Form 28-C",
                    active=True,
                ),
                ComponentShelfLifeRule(
                    component="CRYOPRECIPITATE",
                    storage_method="Frozen at -18°C or colder; thawed at 37°C prior to transfusion",
                    shelf_life_value=365,
                    shelf_life_unit="DAYS",
                    regulatory_reference="DGHS Blood Transfusion Safety Regulations",
                    active=True,
                ),
                ComponentShelfLifeRule(
                    component="WHOLE_BLOOD",
                    storage_method="2°C to 6°C in cold storage with CPDA-1 solution",
                    shelf_life_value=35,
                    shelf_life_unit="DAYS",
                    regulatory_reference="Drugs & Cosmetics Act, 1940 (Rules 122F-122P)",
                    active=True,
                ),
            ]
            db.add_all(rules)
            db.commit()

        # Seed Dynamic System Configurations
        if db.query(SystemConfiguration).count() == 0:
            configs = [
                SystemConfiguration(
                    key="INVENTORY_STALE_HOURS",
                    value="24",
                    data_type="INT",
                    category="INVENTORY",
                    description="Maximum elapsed hours without lab confirmation before inventory is flagged as stale",
                ),
                SystemConfiguration(
                    key="EXPIRY_WARNING_DAYS",
                    value="7",
                    data_type="INT",
                    category="EXPIRY",
                    description="Days remaining threshold triggering APPROACHING_EXPIRY status tier",
                ),
                SystemConfiguration(
                    key="EXPIRY_CRITICAL_DAYS",
                    value="3",
                    data_type="INT",
                    category="EXPIRY",
                    description="Days remaining threshold triggering HIGH_EXPIRY_RISK status tier",
                ),
                SystemConfiguration(
                    key="SHORTAGE_THRESHOLD_MULTIPLIER",
                    value="1.2",
                    data_type="FLOAT",
                    category="PREDICTION",
                    description="Safety buffer multiplier applied to forecasted demand when computing shortage risk",
                ),
                SystemConfiguration(
                    key="MIN_SAFETY_STOCK_UNITS",
                    value="5",
                    data_type="INT",
                    category="SAFETY_STOCK",
                    description="Minimum acceptable threshold of confirmed compatible units before critical alert triggers",
                ),
                SystemConfiguration(
                    key="WASTAGE_RISK_THRESHOLD",
                    value="0.15",
                    data_type="FLOAT",
                    category="WASTAGE",
                    description="Predicted wastage risk probability above which clinical alerts are escalated",
                ),
            ]
            db.add_all(configs)
            db.commit()

        # Seed Wastage Records
        if db.query(WastageRecord).count() == 0:
            banks = db.query(BloodBank).all()
            records = []
            for idx, bank in enumerate(banks[:5]):
                records.extend([
                    WastageRecord(
                        blood_bank_id=bank.id,
                        blood_group=BloodGroup.O_POS,
                        component=ComponentType.PLATELETS,
                        quantity=3,
                        reason="EXPIRY",
                        recorded_at=today - timedelta(days=5),
                        notes="Platelet units exceeded 5-day shelf life during weekend routine hold",
                    ),
                    WastageRecord(
                        blood_bank_id=bank.id,
                        blood_group=BloodGroup.B_POS,
                        component=ComponentType.PRBC,
                        quantity=2,
                        reason="TTI_REACTIVE",
                        recorded_at=today - timedelta(days=12),
                        notes="ELISA screening reactive for HBsAg; standard biohazard disposal per protocol",
                    ),
                ])
            db.add_all(records)
            db.commit()

        print(f"Database seeded successfully! {len(VERIFIED_FACILITIES)} verified facilities and {len(inventory_items)} simulated inventory units created.")

    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
